### ISSUE TITLE
tags in different mixins don't merge

### ISSUE THREAD

**Issue by lamdor** [Banno/knife-whisk#5]
If I have:

``` yaml
mixins:
   staging:
     tags:
       environment: staging
   hbase:
     tags:
       hbase: true

servers:
  example:
    mixins: [staging, hbase]
```

when I do a `knife whisk generate example`, the tags part isn't merged and is outputted as a ruby hash, not the `knife ec2 server create --tags` format.
